### ISSUE TITLE
Weird looking UMAP for spectral flow data

### ISSUE THREAD

**Issue by fingeram** [jlmelville/uwot#106]
Hi, 

I am trying to generate a uwot:umap for spectral flow data (transformed by arcsinh method) but my UMAP always looks super weird, i.e. some clusters showing up in the middle of the plot but a "cloud" of non-clustered cells around it. I use a defined subset of atibodies/markers for the umapping. I tried different parameters for n_neighbors, spread, min_dist, a, and b or using nearest neighbor from tumap for nn_method  but this does not help with the general shape of the UMAP. 

Would be happy about any suggestions!! Thank you. Below is my code 

>fcs_transform_small <- Downsampling_FlowSet(fcs_transform_QC,samplesize = 10000)
>sce_small <- prepData(fcs_transform_small,md=md_2,panel=panel,FACS=T,transform=F, 
                md_cols=list(file="file_name",id="sample_id",factors=colnames(md_2)[-c(1:2)]))
>assayNames(sce_small)[1] <- "exprs"
>exprs_small <- assay(sce_small,"exprs")
>exprs_small <- t(exprs_small)
>exprs_small <- exprs_small[,c(marker_state)]
>set.seed(1234)
>umap_small_uwot <- uwot::umap(exprs_small,pca=ncol(exprs_small), scale=F, 
                              verbose=T, n_neighbors = 50, spread=0.5, min_dist=0.01)
>reducedDim(sce_small,"UMAP1") <- umap_small_uwot
>plotDR(sce_small, "UMAP1",color_by = "donor") +
  scale_color_manual(values = c("yellow","lightblue","red","green","pink")) +
  theme_void(base_size = 15) +
  labs(title="Baseline") +
  geom_point(size=0.1, alpha=1/100)

<img width="779" alt="Bildschirm­foto 2023-02-07 um 22 40 25" src="https://user-images.githubusercontent.com/122848332/217453858-9f5a7d5a-d672-42fe-a790-caf91febec60.png">

**Comment by SamGG** [comment]
Hi,

1) Long story short: IMHO the data are not transformed. Details below.
2) If you use a pipeline, please submit an issue in the github of the pipeline, not in the github of a tool used in the pipeline, especially when the tool (uwot::umap) proved its usefulness and robustness so many times.
3) Please, consider closing this issue once it's solved.

Hope the following will help you.
Best.

I don't see where the classical asinh(x/cofactor) is applied to the channel intensities x, with a cofactor typically equal to 5000.
It seems you used the pipeline described at https://github.com/HdBraanker/Spectral_Flow_Workflow/blob/main/script.Rmd from the article of [den Braanker et al.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8640183/).
From your code, I think your code lacks of the transformation step either by automatic estimation of cofactors
```
cofactors <- estParamFlowVS(fcs_data_small, channels=markerstotransform)
fcs_transform <- transFlowVS(fcs_data, channels = markerstotransform, cofactors)
```
or by setting manually cofactors
```
cofactors<- rep(3000, length(markerstotransform))
fcs_transform <- transFlowVS(fcs_data, channels = markerstotransform, cofactors)
```
Following the code, some of the channels are retained in the transformed data
```
fcs_transform <- fcs_transform[c(1:4,10,16)] #samples from batch A
md <- md[c(1:4,10,16),] # samples from batch A
```
Then this data is subsampled (splitted being more exact, line 286)
```
Subsampling_FlowSet(fcs_transform,0.25, md=md) 
```
Here, the code is misleading because the `Subsampling_FlowSet` function is creating variables `(fcs_train, md_train, fcs_test, md_test)`. So you must execute this function if you want to follow the pipeline and use its next steps from line 294.
Be careful with this "pipeline". In fact, it is a code exploring many aspects of the spectral data processing, but not a pipeline to be executed step by step. If you are looking for something more standard (but without batch correction), I recommend the [CATALYST](https://www.bioconductor.org/packages/release/bioc/html/CATALYST.html) or [FlowSOM](https://www.bioconductor.org/packages/release/bioc/html/FlowSOM.html) pipelines and vignettes.

**Comment by fingeram** [comment]
Hi, 

I am sorry, I was just looking for help not to criticize the uwot package. I would like to clarify, that I DID transform the data (I just did not think it was relevant to my question to include the code, especially since I mentioned that the data I use for umapping is indeed transformed with arcsinh) with channel optimized arcsinh cofactors.  Please find the transformation pipeline, as well as examples of what the data looks like before and after below: 

>markerstotransform <- panel$fcs_colname[c(8:18,20)]
>cofactors <-  estParamFlowVS(fcs_data, channels=markerstotransform)
>fcs_transform <- transFlowVS(fcs_data, channels=markerstotransform, cofactors)

<img width="779" alt="Bildschirm­foto 2023-02-08 um 09 23 34" src="https://user-images.githubusercontent.com/122848332/217605325-5a6611dc-bc66-4964-80a1-1b899054ec89.png">

<img width="779" alt="Bildschirm­foto 2023-02-08 um 09 23 47" src="https://user-images.githubusercontent.com/122848332/217605399-3aa92c28-5db8-401b-b311-63b51b234c16.png">

I did try batch correction but I did not see any batch effects that needed to be corrected. I also performed quality control with PeacoQC. 

That being said, do you have any other recommendations or suggestions why my UMAPs might look this weird? Again I do not think the issue is uwot, I rather think there might be an issue with this spectral flow data so that it cannot be used properly by the uwot algorithm. 

Thanks you!
