### ISSUE TITLE
maybe unintended data use in examples

### ISSUE THREAD

**Issue by topepo** [jlmelville/uwot#116]
In the `umap` examples, `iris30` includes the factor `Species` column. The docs say that this is ok but I wondered if it was intended since there is another example with both `X = iris30` and `y = iris30$Species`. 

Also, I'm not sure about this: 

```r
iris_umap <- umap(iris30, metric = list(
  "euclidean" = c("Sepal.Length", "Sepal.Width"),
  "euclidean" = c("Petal.Length", "Petal.Width")
))
```

since `Species` isn't included. 

I'll be happy to PR to have the examples use `X = iris30[, 1:4]` if that was the intent.

**Comment by jlmelville** [comment]
> In the `umap` examples, `iris30` includes the factor `Species` column. The docs say that this is ok but I wondered if it was intended since there is another example with both `X = iris30` and `y = iris30$Species`.

It's always ok to pass a data frame to `umap`: non-numeric columns will be removed and that includes the factor columns. This is intended as a convenience when you know all the numeric columns should be used in the dimensionality reduction but there are also some factor or character columns that are intended for visualization or supervised learning, in which case it's slightly annoying to have to find and remove them.

In the case where you pass `y = iris30$Species` you are explicitly asking for the supervised UMAP approach, which is the only place you can use a factor column. So the `iris30` input *does* initially contain that column but it gets filtered out.

> Also, I'm not sure about this:
> 
> ```r
> iris_umap <- umap(iris30, metric = list(
>   "euclidean" = c("Sepal.Length", "Sepal.Width"),
>   "euclidean" = c("Petal.Length", "Petal.Width")
> ))
> ```
> 
> since `Species` isn't included.

Hopefully the above makes its a bit clearer: the `Species` column is filtered out, because you can't use a factor column in the standard unsupervised UMAP.

All of these examples should run identically whether you used `iris30` or `iris30[, 1:4]` (or even `iris30[, -5]` if you want to save a keystroke).

**Comment by jlmelville** [comment]
Closing, but please reopen if there is something I haven't understood
