### ISSUE TITLE
Retrieving results from saved R object

### ISSUE THREAD

**Issue by ktmf1991** [jlmelville/uwot#19]
Hi,

This R implementation is very useful for me since I only know R. Thank you for making this package.

So I was trying to run a series of UMAP analysis with different parameters. I saved them with `saveRDS()` for later use, especially for `umap_transform()` function for my testing data set. However, when I retrieve it with `readRDS()` I couldn't use the object as the model for `umap_transform()`. The error message reads:
```
Error in .External(list(name = "CppMethod__invoke_void", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
```
I work on RStudio Server. Not sure if the information helps to solve the problem.

Thanks a lot for making this package again.

**Comment by jlmelville** [comment]
Hi, thanks for the report: it hadn't even occurred to me to think about serializing UMAP models. 

The error you are encountering arises from the use of the RcppAnnoy object, `nn_index`, which is needed for the nearest neighbor search and is wrapping external C++ code:
```R
iris_umap_train <- umap(iris[1:100, ], ret_model = TRUE)
iris_umap_train$nn_index$.pointer
#    <pointer: 0x000000000db3cb10>
```

So far so good. But after saving and reloading:
```R
saveRDS(iris_umap_train, file = "/path/to/somewhere/iris_umap_train.RDS")
iris_umap_train2 <- readRDS(file = "/path/to/somewhere/iris_umap_train.RDS")
iris_umap_train2$nn_index$.pointer
#    <pointer: (nil)>
```

I'm afraid I don't currently have a good solution to this. RcppAnnoy classes have their `save` and `load` methods, so one potential solution for simple cases with just one metric is to manually save the `nn_index` item manually:

```R
saveRDS(iris_umap_train, file = "/path/to/somewhere/iris_umap_train.RDS")
iris_umap_train$nn_index$save("/path/to/somewhere/iris_umap_train.nn_annoy")
```

Then to reload the model, you need to also create a new RcppAnnoy class and then load the data:

```R
iris_umap_train2 <- readRDS(file = "/path/to/somewhere/iris_umap_train.RDS")
iris_umap_train2$nn_index <- methods::new(RcppAnnoy::AnnoyEuclidean, 4)
iris_umap_train2$nn_index$load("/path/to/somewhere/iris_umap_train.nn_annoy")

# this should now work
iris_umap_test <- umap_transform(iris[101:150, ], iris_umap_train2)
```

This is annoying even in this simple case because you have to remember the metric you used (although you can see this in the `metric` item in the model), the name of the equivalent RcppAnnoy class and provide a dimensionality value to the constructor (even though this gets replaced when the `load` method is called). I could wrap these in `load_uwot_model` and `save_uwot_model` functions if this is useful.

Otherwise, I will have to see what I can find about serializing externally stored C++ data and if there are serialization hooks that can be defined to allow `saveRDS` and `readRDS` to work.

**Comment by ktmf1991** [comment]
Thank you for the solution. It works for me and I will be using it at the moment. I would be nice to have the two extra functions if possible. Although I am not sure if everyone does it, I always save results if I am working with methods generating different outcome every time (e.g. t-SNE). So the two functions you proposed will definitely be useful for some users.

**Comment by jlmelville** [comment]
I've added `save_uwot` and `load_uwot` functions with the latest commit. Hopefully these help.

**Comment by jlmelville** [comment]
This *was* an enhancement. But I am repurposing the issue to deal with some bugs unearthed by work on #31:

* Trying to save models with a relative path e.g. `file = 'mymodel'` just doesn't work correctly. The model file is saved in the temporary directory and never moved. You have no way of knowing where that model is after it's saved, so you can't reload it.
* Cleaning up afterwards for both save and load also doesn't work, at least in RStudio on Windows, because the session is apparently still using the serialized indices.
* As noted in #31, loading Annoy indexes shouldn't work when using only one metric.

**Comment by jlmelville** [comment]
uwot 0.1.8 should help with some of these issues to the extent it's possible. Closing again.
