### ISSUE TITLE
Integrating HSNE?

### ISSUE THREAD

**Issue by SamGG** [jlmelville/uwot#38]
Hi,
Thanks for your invaluable work proposing umap in a native R package. Thanks also for the smallvis package.
As you already integrated largeVis and proposed tumap, I am wondering if you planned to integrate HSNE someday. [HDI](https://github.com/Nicola17/High-Dimensional-Inspector) is already integrated in interactive exploration tools such as [cytosplore](https://www.cytosplore.org/), but no R package is available. If you plan it, let me know.
Best.

**Comment by jlmelville** [comment]
Hello, thanks for the suggestion. I don't have plans for HSNE in uwot specifically, because being a t-SNE variant, none of the optimization code would work with it. Also, I don't currently have a work flow that uses uwot in the interactive way suggested by HSNE, so it would be hard for me to design, implement test and maintain the necessary additions to the already quite-bloated uwot API.

However, the Markov chain landmark part of it looks quite interesting. I'd have to spend a lot more time understanding it, but if it could be adapted to UMAP and used as a way of doing a good global initialization as an alternative to the PCA or spectral initialization, that would be very useful. That part at least is something I need to take a closer look at.

**Comment by SamGG** [comment]
Thanks for your feedback. I didn't meant building an interactive software. I was just wondering about compiling the code and offering it as a an alternate tSNE method that uses a hierarchical approach.
It sounds good if my proposal has attracted your interest in some parts of HSNE.
Best.
