### ISSUE TITLE
how to extract features and understand feature importance after running umap from uwot

### ISSUE THREAD

**Issue by ML33M** [jlmelville/uwot#60]
Hi, sorry I'm a noob. I did some grid search and visualized my data 8890 rows/sample and 131 columns (col 21-131 are actual features, 1:20 are labels) on umap. 

So after visualization, I want to know what features are the important ones after umap dimension reduction that I can then build a decision tree to do classification for unknown data, so I know what unknown labels are similar to what labels used in previous training. Does this make sense?

**Comment by jlmelville** [comment]
Hello, unfortunately there isn't a good way that I know of to do feature importance based on UMAP output.

Perhaps there is some theoretical perspective from topology that suggests a way forward, but I don't know enough about that to say either way. In terms of how UMAP is implemented as an algorithm, there isn't anything obvious like a traditional supervised machine learning model with weighted features to analyse and no obvious place to insert one.

Very roughly you are dealing with an approximation to a series of stitched together overlapping nearest neighbor distances, but there's no re-weighting of the features at any point so each feature would have the same importance as that which went into the distance calculation. So what matters in terms of finding the neighbors is the relative scaling of the input features. But that can all be investigated outside of UMAP itself. If a particular feature has a much larger variance than other features it will dominate the distance calculation and in turn that will be reflected in the UMAP output, but that's not actually a good or informative thing, you should just make sure your data is suitably scaled before running UMAP on it.

Presumably your plan to classify unknown data with a decision tree is because the predictions on new data need to be explainable in some way? If so, doing dimensionality reduction with UMAP may not be a good first step. Otherwise, I would think about methods that estimate variable importance that aren't tied to UMAP per se: if I absolutely had to, I would consider building a random forest model from the original features to predict the UMAP output coordinates, then (assuming a decent RF model resulted) use the variable importance measures intrinsic to random forest to find important features. But I would be very skeptical of anything that it told me if I hadn't taken a good look at the properties of the input features first (variance and other distribution descriptions, inter-correlations and so on). Note that you could do this to the output of *any* dimensionality reduction method and dream up any number of similar related methods. I just don't know if much useful would come out of the effort you would have to put in.
