### ISSUE TITLE
densMAP implementation?

### ISSUE THREAD

**Issue by barveaditya** [jlmelville/uwot#73]
Firstly, excellent implementation. Very quick!! 
Just a question - Any chances of incorporating densMAP into this library as well? https://www.nature.com/articles/s41587-020-00801-7

It has apparently been integrated into the Python UMAP lib (https://github.com/hhcho/densvis). From what I understand, the local radius is adaptive to the density of points.

**Comment by LTLA** [comment]
In the meantime, you might like to try out https://bioconductor.org/packages/release/bioc/html/densvis.html, which just wraps the Python implementation into an R-flavored wrapper.

**Comment by jlmelville** [comment]
Currently I have no plans to add densMAP. The implementation would require adding extra routines to the generic optimization code which would in principle affect all other methods, so the testing burden is quite high.

But it is more a question of a lack of spare time and motivation, so never say never.

**Comment by jlmelville** [comment]
Update: I still have no plans to add densMAP to uwot. *But* I have been experimenting with an approximation to it which seems... fine.

Instead of adding an extra objective to the cost function, vary the `a` parameter in the output weight function per-observation to reflect the relative size of the radius in the input space. This pushes points in the denser parts of the data closer together. That's the whole idea. If I get hit by a bus before finishing this (or I just take too long) someone else just feel free to try that out for themselves.

This is a note to myself in public that will hopefully provide me with the motivation to actually finish it or discover the fatal flaw that leads me to abandon it completely.

**Comment by jlmelville** [comment]
On the master branch the promised approximation to densMAP is now available. Set `dens_weight = 1` when you call the `umap` function. The closer that number goes to `0` the closer the output is to plain old UMAP.

Many examples of densMAP and the equivalent in uwot can be seen at this [documentation](https://jlmelville.github.io/uwot/leopold.html). 

This is the closest I will get to implementing densMAP in the near future.

**Comment by barveaditya** [comment]
Oh but this is brilliant. I also see that leopold does a better job where
densMap does not. Thank you James.

Best
Adi

**Comment by jlmelville** [comment]
>  I also see that leopold does a better job where densMap does not.

I wouldn't claim that leopold does better than densMAP. I expect densMAP will always do better if you take the time to tune the `dens_lambda` parameter. But if leopold is sufficient for your needs especially after having waited over a year then that's good enough for me!

**Comment by jlmelville** [comment]
Closing this for now, because future-me is still not inclined to implement densMAP any more than past-me was.
