### ISSUE TITLE
can't find object 'mnist'

### ISSUE THREAD

**Issue by jielab** [jlmelville/uwot#78]
Dear James：

Please see the screenshot below. It says can't find oubject "mnist".

![捕获](https://user-images.githubusercontent.com/26947455/127604535-edb82432-3f93-4d5f-967f-bb1aa914bdc1.PNG)

Can you please let me know what I missed here?

Best regards,
Jie

**Comment by jlmelville** [comment]
The MNIST digits is a dataset that does not come with the uwot. The comments are intended to indicate that you need to load it from somewhere. If you have the `devtools` package installed, then uncomment the lines above:

```R
devtools::install_github("jlmelville/snedata")
mnist <- snedata::download_mnist()
```

Note that it might take a little while to download.

Where possible, having the input and output pasted as text (like in the code snippet I gave above) rather than a screenshot makes helping with issues a lot easier.
