### ISSUE TITLE
Order of elements is not preserved in subgraph_init

### ISSUE THREAD

**Issue by LTLA** [jlmelville/uwot#82]
`subgraph_init` extracts each component for a separate spectral decomposition:

https://github.com/jlmelville/uwot/blob/698be93c0448770b6050d99cb058b3ee18ae7e88/R/init.R#L217

This is fine, but it then `rbind`s the decompositions together:

https://github.com/jlmelville/uwot/blob/698be93c0448770b6050d99cb058b3ee18ae7e88/R/init.R#L227

without much concern for the original order of observations. This only works if the observations in each component are strictly contiguous, which is unlikely to be the case in general.

Incidentally, one might consider avoiding

https://github.com/jlmelville/uwot/blob/698be93c0448770b6050d99cb058b3ee18ae7e88/R/init.R#L184

which is not parsed correctly when calling `uwot:::spectral_init` outside of the package:

```
Browse[2]> fn_name
[1] ":::"           "uwot"          "spectral_init"
``` 

Doing `eval(match.call()[[1]])` will acquire the function itself for later use, but it may be simpler just to pass `spectral_init` directly to `subgraph_init()`.

**Comment by jlmelville** [comment]
At some point, I must have decided that initializing the disconnected subgraphs recursively doesn't really solve the problem around creating an initial layout because there's no way to know how to arrange the results relative to each other, because over at:

https://github.com/jlmelville/uwot/blob/03849978910cfcb8a585cb355827772bd5d09236/R/uwot.R#L1533-L1545

I added a check to disallow graph Laplacian-based initialization in the event of disconnection.

I think the correct thing to do is to remove the recursive code path entirely.

**Comment by jlmelville** [comment]
As noted above I don't think the problematic code could have been reached via the public uwot API so I have deleted it (and with it my bad coding choices). I think this closes the issue, but please re-open if necessary.

**Comment by LTLA** [comment]
Makes sense to me. I'll also delete the corresponding code in **umappp**.
